### ISSUE TITLE
Pillow, reference-files and format which are not supported?

### ISSUE THREAD

**Issue by ValdemarOtte** [aarhusstadsarkiv/acacore#48]
Under `acacore/acacore/utils/functions.py` ved funktionen `image_size` gør vi brug af `Pillow`. Dog, så understøtter `Pillow `kun `PNG`, `JPEG`, `JPEG2000`, `GIF`, `TIFF`, `SVG`, `Netpbm`, `WebP` og `BMP`. 

Dette skaber problemer, da hvis i `reference-files` står en puid's convert tool som `image`, så vil programmet (af hvad jeg forstår af det) åben billedet for at tjekke dens størrelse. Men hvis det ikke er en format som `Pillow `understøtter, så giver `Pillow `en `raise UnidentifiedImageError(msg)`

Jeg har fundet fejlen pga. aflevering 83, hvor fmt/881 med extension `.mdi` gør, at `digiarch identify .` fejler og afslutter programmet helt, når den prøver at identificerer den pågældende file.

**Comment by MatteoCampinoti94** [comment]
Det har intet at gøre med convert.

Denne fejl sker, fordi vi har `ignore_if.image_pixels_min: 20000` i fileformats, så acacore bruger imagesize/Pillow for at finde ud, hvor stor billedet er.

Først, digiarch skal catch `UnidentifiedImageError` og ikke stoppe identificering.

Anden, vi kan fjerne `ignore_if.image_pixels_min` fra fmt/881, hvis vi er sikker at Pillow ikke kan identificere denne format.

**Comment by MatteoCampinoti94** [comment]
Det er det, der gøres :)

https://github.com/aarhusstadsarkiv/acacore/blob/6e3bbfe10494dbf7a15c012a1ae3c32e1825d6a2/acacore/utils/functions.py#L130-L148

**Comment by MatteoCampinoti94** [comment]
Nej, det støtter kun PNG, JPEG, JPEG2000, GIF, TIFF, SVG, Netpbm, WebP.
