### ISSUE TITLE
Image size failed to recognize jpeg size

### ISSUE THREAD

**Issue by Oest1980** [aarhusstadsarkiv/acacore#55]
get_image_size(path)  raise ValueError("Invalid JPEG file")

men stifinder kan godt give størrelse og dpi.
![RES01694](https://github.com/user-attachments/assets/c04aa84b-ced3-4962-a924-7f94fe644d27)

**Comment by mgenware** [comment]
@Oest1980 the photo seems corrupted, there's an extra `0x36 0x00` between 2 jpeg markers:

<img width="618" alt="image" src="https://github.com/user-attachments/assets/d46c3d6f-bae8-4187-ba63-1ec8f4f4e19f">

**Comment by Oest1980** [comment]
@mgenware Thanks :)
