### ISSUE TITLE
Add enum 'Action', which predefines all possible values for the Action field

### ISSUE THREAD

**Issue by Magniler** [aarhusstadsarkiv/acacore#9]
We have now defined the action field, but we need tight control over the possible values this field can have. Therefore we should define an `Enum` of possible actions as `str`s.

The actions should have the following syntax:

[Tool/Manual]: [Act]. [Info]

Soo, first we define what tool should take the action. Then we describe the act in one sentence. The next sentence is additional information.

The following are my proposals for actions. We definatly need more than these, but they can serve as a start and examples:

- Convertool: To convert.
- Convertool: Replace with template. File is not preservable.
- Manual: File should be converted manually. [info about the manual conversion from reference_files].
- Renamer: File has extension mismatch. Should be renamed
(I know renamer might not be able to do it automatically, soo this might need to be a manual process to, but we might be able to solve it)

**Comment by rohitverma007** [comment]
Missed the self-assigned tag, had a go at it, let me know how it looks.
